-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 00:53:26 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_codejunior
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_codejunior
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_codejunior` DEFAULT CHARACTER SET utf8 ;
USE `db_codejunior` ;

-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_desarrollador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_desarrollador` (
  `id_desarrollador` INT NOT NULL AUTO_INCREMENT,
  `desarrollador_nombre` VARCHAR(50) NOT NULL,
  `desarrollador_apellido` VARCHAR(50) NOT NULL,
  `desarrollador_cargo` VARCHAR(100) NOT NULL,
  `desarrollador_email` VARCHAR(200) NOT NULL,
  `desarrollador_contraseña` VARCHAR(200) NOT NULL,
  `desarrollador_telefono` INT NULL,
  `desarrollador_descripcion` LONGTEXT NULL,
  `desarrollador_foto` VARCHAR(250) NULL,
  PRIMARY KEY (`id_desarrollador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_experiencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_experiencia` (
  `id_experiencia` INT NOT NULL AUTO_INCREMENT,
  `experiencia_empresa` VARCHAR(50) NOT NULL,
  `experiencia_cargo` VARCHAR(100) NOT NULL,
  `experiencia_finicio` DATE NOT NULL,
  `experiencia_ffin` DATE NULL,
  `experiencia_logo` VARCHAR(45) NULL,
  `tbl_desarrollador` INT NOT NULL,
  PRIMARY KEY (`id_experiencia`),
  CONSTRAINT `fk_tbl_experiencia_tbl_desarrollador`
    FOREIGN KEY (`tbl_desarrollador`)
    REFERENCES `db_codejunior`.`tbl_desarrollador` (`id_desarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_educacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_educacion` (
  `id_educacion` INT NOT NULL AUTO_INCREMENT,
  `educacion_institucion` VARCHAR(150) NOT NULL,
  `educacion_carrera` VARCHAR(100) NOT NULL,
  `educacion_certificado` VARCHAR(250) NULL,
  `educacion_foto` VARCHAR(250) NULL,
  `tbl_desarrollador` INT NOT NULL,
  PRIMARY KEY (`id_educacion`),
  CONSTRAINT `fk_tbl_educacion_tbl_desarrollador1`
    FOREIGN KEY (`tbl_desarrollador`)
    REFERENCES `db_codejunior`.`tbl_desarrollador` (`id_desarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_redes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_redes` (
  `id_redes` INT NOT NULL AUTO_INCREMENT,
  `redes_redes` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_redes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_desarrollador_redes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_desarrollador_redes` (
  `id_desarrollador_redes` INT NOT NULL AUTO_INCREMENT,
  `desarrollador_redes_url` VARCHAR(250) NOT NULL,
  `tbl_desarrollador` INT NOT NULL,
  `tbl_redes` INT NOT NULL,
  PRIMARY KEY (`id_desarrollador_redes`),
  CONSTRAINT `fk_tbl_desarrollador_redes_tbl_desarrollador1`
    FOREIGN KEY (`tbl_desarrollador`)
    REFERENCES `db_codejunior`.`tbl_desarrollador` (`id_desarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_desarrollador_redes_tbl_redes1`
    FOREIGN KEY (`tbl_redes`)
    REFERENCES `db_codejunior`.`tbl_redes` (`id_redes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_tecnologia` (
  `id_tecnologia` INT NOT NULL AUTO_INCREMENT,
  `tecnologia_nombre` VARCHAR(50) NOT NULL,
  `tecnologia_imagen` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_tecnologia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_desarrollador_tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_desarrollador_tecnologia` (
  `idtbl_desarrollador_tecnologia` INT NOT NULL AUTO_INCREMENT,
  `tbl_desarrollador` INT NOT NULL,
  `tbl_tecnologia` INT NOT NULL,
  PRIMARY KEY (`idtbl_desarrollador_tecnologia`),
  CONSTRAINT `fk_tbl_desarrollador_tecnologia_tbl_desarrollador1`
    FOREIGN KEY (`tbl_desarrollador`)
    REFERENCES `db_codejunior`.`tbl_desarrollador` (`id_desarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_desarrollador_tecnologia_tbl_tecnologia1`
    FOREIGN KEY (`tbl_tecnologia`)
    REFERENCES `db_codejunior`.`tbl_tecnologia` (`id_tecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_empresa` (
  `id_empresa` INT NOT NULL AUTO_INCREMENT,
  `empresa_razon_social` VARCHAR(100) NOT NULL,
  `empresa_ruc` VARCHAR(11) NOT NULL,
  `empresa_telefono` INT NULL,
  `empresa_descripcion` LONGTEXT NOT NULL,
  `empresa_foto` VARCHAR(250) NULL,
  `empresa_encargado` VARCHAR(100) NOT NULL,
  `empresa_email` VARCHAR(250) NOT NULL,
  `empresa_contraseña` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_trabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_trabajos` (
  `id_trabajos` INT NOT NULL AUTO_INCREMENT,
  `trabajos_cargo` VARCHAR(45) NOT NULL,
  `trabajos_modalidad` VARCHAR(45) NOT NULL,
  `trabajos_jornada` VARCHAR(45) NOT NULL,
  `trabajos_salario` VARCHAR(45) NULL,
  `trabajos_publicado` VARCHAR(45) NOT NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`id_trabajos`),
  CONSTRAINT `fk_tbl_trabajos_tbl_empresa1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_codejunior`.`tbl_empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_desarrollador_trabajos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_desarrollador_trabajos` (
  `idtbl_desarrollador_trabajos` INT NOT NULL AUTO_INCREMENT,
  `desarrollador_trabajos_chat` VARCHAR(1) NULL,
  `id_desarrollador` INT NOT NULL,
  `id_trabajos` INT NOT NULL,
  PRIMARY KEY (`idtbl_desarrollador_trabajos`),
  CONSTRAINT `fk_tbl_desarrollador_trabajos_tbl_desarrollador1`
    FOREIGN KEY (`id_desarrollador`)
    REFERENCES `db_codejunior`.`tbl_desarrollador` (`id_desarrollador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_desarrollador_trabajos_tbl_trabajos1`
    FOREIGN KEY (`id_trabajos`)
    REFERENCES `db_codejunior`.`tbl_trabajos` (`id_trabajos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_trabajos_tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_trabajos_tecnologia` (
  `id_trabajos_tecnologia` INT NOT NULL AUTO_INCREMENT,
  `id_tecnologia` INT NOT NULL,
  `id_trabajos` INT NOT NULL,
  PRIMARY KEY (`id_trabajos_tecnologia`),
  CONSTRAINT `fk_tbl_puesto_trab_tecnologia_tbl_tecnologia1`
    FOREIGN KEY (`id_tecnologia`)
    REFERENCES `db_codejunior`.`tbl_tecnologia` (`id_tecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_trabajos_tecnologia_tbl_trabajos1`
    FOREIGN KEY (`id_trabajos`)
    REFERENCES `db_codejunior`.`tbl_trabajos` (`id_trabajos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_empresa_red`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_empresa_red` (
  `idtbl_empresa_red` INT NOT NULL AUTO_INCREMENT,
  `empresa_red_url` VARCHAR(45) NOT NULL,
  `id_redes` INT NOT NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`idtbl_empresa_red`),
  CONSTRAINT `fk_tbl_empresa_red_tbl_redes1`
    FOREIGN KEY (`id_redes`)
    REFERENCES `db_codejunior`.`tbl_redes` (`id_redes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_empresa_red_tbl_empresa1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_codejunior`.`tbl_empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_codejunior`.`tbl_empresa_tecnologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_codejunior`.`tbl_empresa_tecnologia` (
  `idtbl_empresa_tecnologia` INT NOT NULL AUTO_INCREMENT,
  `id_tecnologia` INT NOT NULL,
  `id_empresa` INT NOT NULL,
  PRIMARY KEY (`idtbl_empresa_tecnologia`),
  CONSTRAINT `fk_tbl_empresa_tecnologia_tbl_tecnologia1`
    FOREIGN KEY (`id_tecnologia`)
    REFERENCES `db_codejunior`.`tbl_tecnologia` (`id_tecnologia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_empresa_tecnologia_tbl_empresa1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `db_codejunior`.`tbl_empresa` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
